# This runs the pre-commit hook logic to check whether the relevent
# CHANGELOG.md files have been updated for both the root directory
# and/or modules edited if they have been changed.

name: Validate Changelogs

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - ".github/**"
      - ".githooks/**"
      - "docs/**"
      - "bin/**"

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT

  validate:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # Map a step output to a job output
    outputs:
      result: ${{ steps.verify_changelogs.outputs.result }}
    # only run if there are changed files
    if: ${{needs.changedfiles.outputs.all}}
    steps:
      - uses: actions/checkout@v3
      - name: Verify changelogs
        id: verify_changelogs
        run: bash ./.githooks/pre-receive "${{needs.changedfiles.outputs.all}}"

  review:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: validate
    steps:
      - name: Verify changelogs KO
        if: ${{ contains(needs.validate.outputs.result, 'failed') }}
        uses: actions/github-script@v5
        with:
          script: |
            const result = `<!-- verify_changelogs_review -->The changelog validation failed with the following output:

            \`\`\`
            ${{ needs.validate.outputs.result }}
            \`\`\`

            Please update the relevant CHANGELOG.md files and ensure they follow the correct format.`;

            await github.rest.pulls.createReview({
              pull_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: result,
              event: "REQUEST_CHANGES",
            });
            process.exit(1);
      - name: Verify changelogs OK - Dismiss review comments
        if: ${{ !contains(needs.validate.outputs.result, 'failed') }}
        uses: actions/github-script@v5
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const uniqueIdentifier = "<!-- verify_changelogs_review -->";

            // List all the reviews on the pull request
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            // Dismiss all reviews containing the unique identifier
            for (const review of reviews) {
              if (review.body.includes(uniqueIdentifier)) {
                await github.rest.pulls.dismissReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                  review_id: review.id,
                  message: "The check succeeded, dismissing the review comment.",
                });
              }
            }
